local builtin = require('telescope.builtin')
local keymap = vim.keymap.set
keymap('n', '<leader>ff', builtin.find_files, {})
keymap('n', '<C-p>', builtin.git_files, {})
keymap('n','<C-s>',builtin.git_commits,{})
keymap('n','<C-b>', builtin.git_branches,{})
keymap('n','<S-a>',builtin.git_status,{})
keymap('n', '<leader>fs', function()
	builtin.grep_string({search = vim.fn.input("Grep > ")})
end)
keymap('n','<leader>d', builtin.diagnostics,{})
